name: Tests
on: [push, pull_request]

jobs:
  test-gradle:
    runs-on: ubuntu-latest
    name: Gradle Check
    steps:
      - uses: actions/checkout@v2
      - uses: cirruslabs/http-cache-action@master
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - run: free -h
      - run: df -h
